[package]
name = "utils"
version = "0.9.5"
authors = ["Leonardo Gibrowski Faé <leonardo.fae44@gmail.com>"]
edition = "2021"
license-file = "../LICENSE"

[dependencies]
# use specific git version for Duration implementation. We will do this until the next bitcode release
bitcode = { git = "https://github.com/SoftbearStudios/bitcode.git", rev = "5f25a59", default-features = false, features = [ "derive" ]}

[build-dependencies]
pkg-config = "0.3"

[dev-dependencies]
rand = "0.8"
criterion = "0.5"

[[bench]]
name = "compression"
harness = false
