[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"
# Certain crates/versions that will be skipped when doing duplicate detection.
skip = []
# Crate dependency trees that will be skipped when doing duplicate detection.
skip-tree = []

[licenses]
# The lint level for crates which do not have a detectable license
allow = [
    "Apache-2.0",
	"Apache-2.0 WITH LLVM-exception", # used by the ravif crate
    "BSD-2-Clause", # used by the ravif crate
    "BSD-3-Clause",
    "GPL-3.0",
    "MIT",
    "Unicode-DFS-2016",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["https://github.com/SoftbearStudios/bitcode.git"]
